# Generated by Django 4.0.3 on 2022-04-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('types', models.CharField(choices=[('FPS', 'First Person Shooter'), ('RPG', 'Role Playing Game'), ('RTS', 'Real Time Strategy'), ('SnS', 'Simulation and Sports')], max_length=3)),
                ('release_date', models.DateTimeField()),
                ('age', models.IntegerField()),
                ('awards', models.ManyToManyField(blank=True, to='games.award')),
            ],
        ),
    ]
