# Generated by Django 4.0.3 on 2022-04-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
